public with sharing class AccountAcc {
    public AccountAcc() {
TestingClass.newTest(); 
method2();
    }
void method2(){
system.debug('Hello From Private');
system.debug('Hello From Private');
system.debug('Hello From Private');
system.debug('Hello From Private');
system.debug('Hello From Private 1');
system.debug('Hello From Private 2');
system.debug('Hello From Private 3');
system.debug('Hello From Private 4');


}
}
