public with sharing class AccountAcc {
public AccountAcc() {
method2(); 
}
void method2(){
system.debug('Hello From Private');  //.more changes
system.debug('Hello From Private');
system.debug('Hello From Private');
system.debug('Hello From Private'); //changes from Git
system.debug('Hello From Private 1');
system.debug('Hello From Private 2');
system.debug('Hello From Private 3');
system.debug('Hello From Private 4');
System.debug('///////////////////////////////////////');


}
}
